name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# give the job permission to push the updated README
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKETYME_API_KEY }}
          TIME_RANGE: last_year
          LANG_COUNT: 10
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_TIME: true
          BLOCKS: "░▒▓█"
          CODE_LANG: txt
